counter=0;
$(".addElevation").click(function(){
  if(counter<5){
  counter++;
  $('.paper-card').attr('elevation',counter);
  }
});
$(".removeElevation").click(function(){
  if(counter>0){
  counter--;
  $('.paper-card').attr('elevation',counter);
  }
});