$(".removeElevation").click(function(){
  counter=$('.paper-card').attr('elevation');
  if(counter>0){
  counter--;
  $('.paper-card').attr('elevation',counter);
  }
});
$(".addElevation").click(function(){
  counter=$('.paper-card').attr('elevation');
  if(counter<5){
  counter++;
  $('.paper-card').attr('elevation',counter);
  }
});